area/urls.py
from django.urls import path, re_path
from .views import *


app_name = 'area'

urlpatterns = [
    path('', area_index, name='area_index'),
    path('pro/', pro, name='area_pro_list'),
    re_path(r'^city_(\d+)/', city, name='area_city_list'),
    path('html_editor/', html_editor),
    path('html_content/', html_content),
]

booktest2/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'booktest'

urlpatterns = [
    path('', index, name='index'),
    # re_path("^(\d+)$", detail, name='detail'),
    re_path("^(\d+)$", show, name='show'),
    path("get_test1/", get_test1),
    path("get_test2/", get_test2),
    path("get_test3/", get_test3),
    path("post_test1/", post_test1),
    path("post_test2/", post_test2),
    path("cookie_test/", cookie_test),
    path("red_test1/", red_test1),
    path("red_test2/", red_test2),
    path("session1/", session1),
    path("session2/", session2),
    path("session2_handle/", session2_handle),
    path("session3/", session3),
    path("template_test/", template_test),
    re_path("^show_hero_detail_(\d+)$", show_hero_detail, name='show_hero_detail'),
    path("child_index/", child_index),
    re_path("^user_(\d+)$", user, name='user'),
    path("html_test/", html_test),
    re_path("^csrf_(\d+)$", csrf_test, name='csrf_test'),
    re_path("^hero_list/(\d*)/?$", hero_list),
    path("cache1/", cache1),
    path("cache2/", cache2),
    path("cache3/", cache3),
    path("search_hero_index/", search_hero_index),
    path("celery_index/", celery_index),
]

django_test/urls.py
from django.contrib import admin
from django.urls import include, path
from verifycode import verify_code

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booktest.urls')),
    path('booktest/', include('booktest2.urls', namespace='booktest')),
    path('verify_code/', verify_code.verify_code),
    path('area/', include('area.urls', namespace='area')),
    path('tinymce/', include('tinymce.urls')),
    path('search/', include('haystack.urls')),
]

booktest2/models.py
from django.db import models


class BookInfoManager(models.Manager):
    def get_queryset(self):
        return super(BookInfoManager, self).get_queryset().filter(isDelete=False)

    # 使用管理器来进行创建新对象
    def create(self, title, pub_date):
        b = BookInfo()
        b.btitle = title
        b.bpub_date = pub_date
        b.bread = 0
        b.bcomment = 0
        b.isDelete = False
        return b


# 注意模型类中不要使用__init__方法，因为在Django中Model类的__init__方法做了很多操作
class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(db_column='pub_date')
    bread = models.IntegerField(default=0)
    bcomment = models.IntegerField(null=False)
    isDelete = models.BooleanField(default=False)

    class Meta(object):
        db_table = 'bookinfo'  # 指定表名
        # ordering = ['id']  # 指定默认排序字段

    books1 = models.Manager()  # 修改默认管理器，取代默认的objects
    books2 = BookInfoManager()  # 自定义管理器对象

    # 使用类方法进行创建新对象，推荐使用管理器方法进行创建
    @classmethod
    def create(cls, title, pub_date):
        b = BookInfo()
        b.btitle = title
        b.bpub_date = pub_date
        b.bread = 0
        b.bcomment = 0
        b.isDelete = False
        return b


class HeroInfo(models.Model):
    hname = models.CharField(max_length=10)
    hgender = models.BooleanField(default=True)
    hcontent = models.CharField(max_length=1000)
    isDelete = models.BooleanField(default=False)
    book = models.ForeignKey(BookInfo, on_delete=models.CASCADE)

    def showname(self):
        return self.hname

booktest2/views.py
from django.shortcuts import render, redirect
from .models import *
from django.db.models import Max, F, Q
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import *
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from . import task


def index(request):
    list = BookInfo.books1.filter(heroinfo__hcontent__contains='六')  # 内联查询
    # list = BookInfo.books1.filter(pk__lt=3)  # 主键小于3的

    # 使用F对象来比较两列，同时F对象支持运算
    # list = BookInfo.books1.filter(bread__gt=F('bcomment'))

    # 使用Q对象来实现逻辑或
    # list = BookInfo.books1.filter(Q(pk__lt=4) | Q(btitle__contains="1"))

    max_date = BookInfo.books1.aggregate(Max('bpub_date'))  # 聚合

    context = {
        "list1": list,
        "max_date": max_date
    }
    return render(request, 'booktest2/index.html', context)


def detail(request, pi):
    return HttpResponse(pi)


# 展示链接的页面
def get_test1(request):
    return render(request, 'booktest2/getTest1.html')


# 展示一键一值的情况
def get_test2(request):
    # 根据键接收值
    a = request.GET['a']
    b = request.GET['b']
    c = request.GET['c']

    # 构造上下文
    context = {'a': a, 'b': b, 'c': c}

    # 向模板中传递上下文，并进行渲染
    return render(request, 'booktest2/getTest2.html', context)


# 展示一键多值的情况
def get_test3(request):
    a = request.GET.getlist('a')
    context = {'a': a}
    return render(request, 'booktest2/getTest3.html', context)


def post_test1(request):
    return render(request, 'booktest2/postTest1.html')


def post_test2(request):
    uname = request.POST['uname']
    upwd = request.POST['upwd']
    ugender = request.POST['ugender']
    uhobby = request.POST.getlist('uhobby')
    context = {'name': uname, 'pwd': upwd, 'gender': ugender, 'hobby': uhobby}
    return render(request, 'booktest2/postTest2.html', context)


# 注意：跨域名无法共享cookie信息
def cookie_test(request):
    response = HttpResponse()
    cookies = request.COOKIES
    if cookies['t1']:
        response.write(cookies['t1'])
    # response.set_cookie('t1', 'abc')
    return response


def red_test1(request):
    # return HttpResponseRedirect('/booktest/red_test2/')
    return redirect('/booktest/red_test2/')


def red_test2(request):
    return HttpResponse('这是重定向来的页面')


# 通过用户登录练习session
def session1(request):
    name = request.session.get("myname", '未登录')
    context = {"name": name}
    return render(request, 'booktest2/session1.html', context)


def session2(request):
    return render(request, 'booktest2/session2.html')


def session2_handle(request):
    uname = request.POST['uname']
    request.session['myname'] = uname
    request.session.set_expiry(0)  # 设置session失效时间，为0则浏览器关闭就失效
    return redirect('/booktest/session1/')


def session3(request):
    if 'myname' in request.session.keys():
        del request.session['myname']
    # request.session.flush()  # 清空session和cookie
    return redirect('/booktest/session1/')


def template_test(request):
    # hero = HeroInfo.objects.get(pk=1)
    # context = {'hero': hero}

    list = HeroInfo.objects.all()
    context = {'list': list}
    return render(request, 'booktest2/template_test.html', context)


def show(request, id):
    context = {'id': id}
    return render(request, 'booktest2/show.html', context)


def show_hero_detail(request, hero_id):
    hero = HeroInfo.objects.get(pk=hero_id)
    context = {'hero': hero}
    return render(request, 'booktest2/show_hero_detail.html', context)


def child_index(request):
    return render(request, 'booktest2/child_index.html')


def user(request, index):
    if '1' == index:
        return render(request, 'booktest2/user_first.html')
    elif '2' == index:
        return render(request, 'booktest2/user_second.html')
    else:
        return HttpResponse('什么都没有匹配')


# html转移
def html_test(request):
    context = {'t1': '<h1>t1</h1>'}
    return render(request, 'booktest2/html_test.html', context)


# csrf
def csrf_test(request, index):
    if '1' == index:
        return render(request, 'booktest2/csrf1.html')
    elif '2' == index:
        name = request.POST['name']
        context = {'name': name}
        return render(request, 'booktest2/csrf2.html', context)
    else:
        return HttpResponse('路径错误')


def hero_list(request, pindex):
    if pindex == '':
        pindex = '1'
    list = HeroInfo.objects.all()
    paginator = Paginator(list, 5)
    page = paginator.page(int(pindex))
    context = {'page': page}
    return render(request, 'booktest2/hero_list.html', context)


# 缓存视图
@cache_page(60)
def cache1(request):
    print("使用cache")
    return HttpResponse('hello1')


# 缓存模板
def cache2(request):
    print("使用cache")
    return render(request, 'booktest2/cache2.html')


# 自定义缓存数据
def cache3(requst):
    # cache.set('key1', 'value1', 600)
    # print(cache.get('key1'))
    cache.clear()  # 清空缓存
    return render(requst, 'booktest2/cache2.html')


# 全文检索 + 中文分词
def search_hero_index(request):
    return render(request, 'booktest2/search_hero.html')


# celery
def celery_index(request):
    # task.show()
    task.show.delay()
    return HttpResponse("ok")

templates/booktest2/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模板</title>
    {% block head %}
    {% endblock %}
</head>
<body>

<h1>logo</h1>
<hr>

{% block content1 %}
    <h1>这是预留的坑</h1>
{% endblock %}

<hr>

<h1>contact</h1>

</body>
</html>

templates/booktest2/base_goods.html
{% extends 'booktest2/base.html' %}

{% block content1 %}
    <table border="1">
    <tr>
        <td height="300">推荐商品</td>
        <td>{% block goods_conent %}{% endblock goods_conent %}</td>
    </tr>
    </table>

{% endblock content1 %}

templates/booktest2/base_user.html
{% extends 'booktest2/base.html' %}

{% block content1 %}
    <table border="1">
    <tr>
        <td height="300">用户导航</td>
        <td>{% block user_conent %}{% endblock user_conent %}</td>
    </tr>
    </table>

{% endblock content1 %}

templates/booktest2/cache2.html
{% load cache %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>缓存模板</title>
</head>
<body>

{% cache 60 hello %}
hello1
{% endcache %}

</body>
</html>

templates/booktest2/csrf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>csrf</title>
</head>
<body>

<form action="{% url 'booktest:csrf_test' '2' %}" method="post">
    {# 通过csrf_token标签来处理csrf认证问题，只有POST需要处理 #}
    {% csrf_token %}
    <input type="text" name="name">
    <input type="submit" value="提交">
</form>

</body>
</html>

templates/booktest2/getTest2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>getTest2</title>
</head>
<body>
a:{{ a }}
<br>
b:{{ b }}
<br>
c:{{ c }}

</body>
</html>

templates/booktest2/hero_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>英雄列表</title>
</head>
<body>

<ul>
    {% for hero in page %}
        <li>{{ hero.hname }}</li>
    {% endfor %}
</ul>

<hr>

{% for index in page.paginator.page_range %}
    {% if index == page.number %}
        {{ index }}
    {% else %}
        <a href="/booktest/hero_list/{{ index }}">{{ index }}</a>
    {% endif %}
{% endfor %}

</body>
</html>

templates/booktest2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
<ul>
    {% for book in list1 %}
        <li>{{ book.btitle }} -- {{ book.bread }} -- {{ book.bcomment }}</li>
    {% endfor %}

    <hr>

    {{ max_date }}

    <hr>

    {# 使用url进行反向解析 格式 namespace:urlpathname params1 params2...  params数量与方法一致#}
    <a href="{% url 'booktest:show' '123' %}">显示</a>
</ul>
</body>
</html>

templates/booktest2/postTest2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>postTest2</title>
</head>
<body>

用户名：{{ nmae }}<br>
密码：{{ pwd }}<br>
性别：{{ gender }}<br>
爱好：
{% for item in hobby %}
    {{ item }}
{% endfor %}

<br>

</body>
</html>

templates/booktest2/session1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>session</title>
</head>
<body>
你好：{{ name }}
<br>

<a href="/booktest/session2/">登录</a>
<a href="/booktest/session3">退出</a>
</body>
</html>

templates/booktest2/session2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>session2</title>
</head>
<body>
    <form method="post" action="/booktest/session2_handle/">
        <input type="text" name="uname">
        <br>
        <input type="submit" name="登录">
    </form>
</body>
</html>

templates/booktest2/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍英雄</title>
</head>
<body>

{% comment %}
{% for hero in list %}
    <h1>hero name is {{ hero.hname }}</h1>
{% endfor %}

{% endcomment %}

{{ id }}

</body>
</html>

templates/booktest2/template_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>template</title>

    <style type="text/css">
        .odd {
            color: red;
        }

        .even {
            color: blue;
        }

    </style>
</head>
<body>
{#{{ hero.hname }}#}

<hr>
奇数行为红色，偶数行为蓝色
<hr>

<ul>
    {% for hero in list %}
        <li>
            {% if forloop.counter|divisibleby:2 %}
                <a class="even"
                   href="{% url 'booktest:show_hero_detail' hero.id %}">{{ forloop.counter }}:{{ hero.showname }}</a>
            {% else %}
                <a class="odd"
                   href="{% url 'booktest:show_hero_detail' hero.id %}">{{ forloop.counter }}:{{ hero.showname }}</a>
            {% endif %}
        </li>
    {% empty %}
        什么也没有
    {% endfor %}
</ul>
</body>
</html>

templates/booktest2/user_first.html
{% extends 'booktest2/base_user.html' %}

{% block user_conent %}
    这是第一个用户的数据
{% endblock user_conent %}